language: php
php:
- 7.1
- 7.2
env:
  matrix:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""
  global:
  - secure: BZR5IRtIszvc+HLVPWJgXOeqnj1AzSJzbdSOboh2LV7/em/YicMZkWiM+Xo/sNGaqa6bKnC7iHL7VSHX6gLY3gZqyzsZXWZy+ztQxpjfLus0vF6kRBREtUhhhHg4SjLD3uuBEyckH7Bdu1bsDkd9W5fwck9R7MRyvGEqYogeX95YijQ38gEPDnvmuolLAepk40zLgw9tRIKmlVAFKQzBjEPCsEIOb/LT39DvBfSv5PEaOkz14HYR6ST5XpJAux5vBHpA2CrhQv+aEy5QmTSgcjPqZ0/4Mgl8pNJ8U37xAkhGpHoGNLldC+Np41VuPPdQHZe3XiY/lrGB0avxP0DoveCM5d6t0Bfy0PZUOPQ5p/SI8eqBGCahm+VkrWI9O+Er1945SVQBuSJcpfmy8qgTOelGhXPKok53yaJBvm6kgGYP3MkAVK4ynozuXREYdy3gWu5Qxx1JeWZwCECLuedC20560UjeExa/utLdBGd0lsUwSvnX+hn64C5Nv0Ss7L+h+mzmgpAwKS76xZAvQI+1VXb7hiF0ujFKJlSmWIfhBwcVPDZ9H1D/2N6IeNV3aNLDQBjiS9hU1oj9vi6dAI0byPuTjqIJOGfS5o2hBQpx2p6v3DtYUK5Gj3BTgFkgWGUKz6GVBTT3/lv/b/ozk5/l9GerstChDKa24ryTTBeVrZ8=
  - secure: c1+jjhBrP+uNS9Ebqqf5+jX/Ljl0PlRRGiwPNHTVZv5U7/kxmaaQSScAx49HRFP30NBiWbIF/YQJjaTQwt750oNoCuZpd10Uv80IAA/aNtArxj+WkBloqDuDSZEElAzCBNiSEvdgDsktHnnavTQMbUBIfd7pT6poVjcXgXlKrrRW1fCyO1Z/Xg0O8mvlAU0L7CQ5gf94sjn/nT8p7oWD16so5iXXNWMHPSTvPJ5EoeCKc83wbzUwlwmDQnvRPIzAvKXHdrZ67haoJ0fUyw8PgEYGk9Nb83J4VCpIJJzyPRiaf6WbwwnbfrDvW2MV7AnsUiSYnrq+K/67FLy25p74QAIfvaUJwZGRGUNp6KQUfEbr8K29ZOomzrMHHP1Tf04e4EvPQG7e78utuRER/0L9pLNsKbnZh05gkHObA6lVxwCdfKPjuSXTeTvW5vizkoCdGgGyHGc1Db6A7wKqpGlq62G5CF32ZFyPxWah4URzPBx9zVOU7TkX1yU66w1DpYUF9olPzxY4XxGJRu/rc7Em2gWqDtI82z/A+VgWVaa9NNtJNvKkHAIcSgKe6E2g4gjd4UKL5SBAxlbJsUzaSpqNxsTLPd1LxoVp0wDcq52Hn2cZzhFmWx4uHVRk6pX3QGguWUQ4EDBmxkfvr8tLlfAWBnfTxsWwZbGZA8BN+jcU8j4=
install:
- echo "{\"http-basic\":{\"nova.laravel.com\":{\"username\":\"${NOVA_USERNAME}\",\"password\":\"${NOVA_PASSWORD}\"}}}"
  > auth.json
before_script:
- travis_retry composer self-update
- travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
script:
- vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
- wget https://scrutinizer-ci.com/ocular.phar
after_script:
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover
